version: 3.0.1
pipeline_os: windows

env:
  - GITHUB_ACCESS_TOKEN_ID: github_access_token_acsbuildguy
  - JENKINS_NODE_WIN: DynamoWinBuild

jenkins_creds:
  -
    type: secretText
    credentialsId: svc_d_dyntest-apikey-artifactory-dynamo-team-nuget
    secretText: API_KEY

code_analysis:
  sonarqube:
    source_encoding: UTF-8
    src: .
    coverage_reports:
      - coverage.info

build:
  -
    scripts:
      - dotnet msbuild src/Autodesk.RefineryToolkits.sln -p:Configuration=Release -p:CopyLocal=False -restore

deployment:
  -
    type: sign
    files_to_sign:
      - build/Refinery Toolkit/bin/Autodesk.RefineryToolkits.*.dll
  -
    type: customized
    scripts:
      - pwsh.exe -ExecutionPolicy ByPass -Command Compress-Archive -Path 'build/Refinery Toolkit' -DestinationPath RefineryToolkit.zip
  -
    type: artifacts
    publish_to_jenkins: true
    publish_to_artifactory: false
    outputs:
      - RefineryToolkit.zip
  -
    type: nuget
    custom_api_key: ${API_KEY}
    nuget_config_file: src/nuget.config
    allow_branches: master
    nuspec_files:
      - RefineryToolkit.nuspec
    package_version_cmd: echo %MS_PACKAGE_VERSION%
    destination_source_name: Dynamo Artifactory
